name: Explain FRU Code

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cpp'
      - '**/*.py'  

jobs:
  explain-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Explain FRU Code
        run: |
          python explain-fru.py
